# Generated by Django 6.0.4 on 2026-04-21 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=500)),
                ('file_ids', models.JSONField()),
                ('backup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size_bytes', models.BigIntegerField()),
                ('parts_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-backup_date'],
            },
        ),
    ]
