# Generated by Django 6.0.4 on 2026-04-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='progress_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='progress_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='file_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='parts_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
